on:
  pull_request:
    paths:
      - "wondrous-app/**/**.ts"
      - "wondrous-app/**/**.js"
    types:
      - opened
      - synchronize

name: Web App - Lint and Test

defaults:
  run:
    working-directory: wondrous-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn lint
      - run: NODE_OPTIONS=--max_old_space_size=4096 yarn build
